### ISSUE TITLE
ambient_profile missing

### ISSUE THREAD

**Issue by dmontielg** [CaibinSh/scAR-reproducibility#1] opened 2022-02-15 13:04 UTC
Hi,

I am following the tutorial provided for denoising CITE-seq and the ambient profile data that is refer in the jupyter notebook is missing: https://github.com/CaibinSh/scAR-reproducibility/blob/main/reproducibility/scAR_tutorial_denoising_CITEseq.ipynb

#ambient_profile = pd.read_pickle('../data/CITEseq_PBMCs_5k_ADT_ambient_profile.pickle')

Thank you,
Diego

**Comment by CaibinSh** [comment] 2022-02-15 14:40
Hi @dmontielg ,

Thanks for reporting this. All relevant data have been integrated into a single h5ad file. Please use the updated tutorial.

I would appreciate if you close the issue when it is fixed. Otherwise, I will close it in about three days assuming the issue is fixed.

Thanks a lot, Caibin

**Closed as completed** 2022-02-16 13:16 UTC
